#!/usr/bin/env bash
#script that setup a nginx web server

sudo apt update -y && apt upgrade -y
sudo apt install nginx -y

echo "Hello world!" >/var/www/html/index.nginx-debian.html

service nginx restart
