#!/usr/bin/env bash
# Script that setup a nginx web server on our server.

sudo apt update -y && apt upgrade -y
sudo apt install nginx -y

sudo echo "Hello world!" >/var/www/html/index.nginx-debian.html

sudo service nginx restart
