#!/usr/bin/env bash
# Script that setup a nginx web server on our server, redirection, 404, header

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo "Hello world!" >/var/www/html/index.nginx-debian.html

# Redirect to 
sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.learnwithmuluante.com permanent;' /etc/nginx/sites-available/default

# 404 Page not Found
curl https://learnwithmuluanteshop >/var/www/html/404.html
sed -i '/learnwithmuluanteshop permanent;$/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Served header
sed -i "/404 \/404.html;$/a\        add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

service nginx restart
