#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and I hate the kill command
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
